[project]
name = "drug-dataset"
version = "0.1.0"
description = "Working with drug data from drugbank and CheMBL"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
	"pandas",
	"rdkit",
	"tqdm",
	"datamol",
	"pyarrow",
	"jupyter",
]
